### ISSUE TITLE
Old version in Chef Supermarket

### ISSUE THREAD

**Issue by jpmat296** [criteo-cookbooks/wsus-client#23]
Link:
https://supermarket.chef.io/cookbooks/wsus-client

Version available on supermarket is 1.2.0
Version in GitHub is 1.2.1

I think you forget to upload latest version to supermarket.

HTH
Jean-Pierre

**Comment by Annih** [comment]
Hello,

Thanks for creating this issue, we are already aware of this situation, we were waiting for the resolution of https://github.com/travis-ci/dpl/pull/443

**Comment by Annih** [comment]
V1.2.1 released :D

**Comment by jpmat296** [comment]
Thanks a lot, it works like a charm :-)
