### ISSUE TITLE
Wsus service always restart when node['wsus_client']['update_group'] is nil

### ISSUE THREAD

**Issue by lbn-chef-team** [criteo-cookbooks/wsus-client#27]
Hello,

meet this problem at each run:
<pre>
Recipe: wsus-client::configure
  * registry_key[HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate] action create
    - set value {:type=>:string, :name=>"TargetGroup", :data=>nil}
  * windows_service[wuauserv] action restart
    - restart service windows_service[wuauserv]
  * powershell_script[Force Windows update detection cycle] action run
    - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/ADMINI~1/AppData/Local/Temp/2/chef-script20170206-2912-qmkai4.ps1"
</pre>

the cause is from:
https://github.com/criteo-cookbooks/wsus-client/blob/master/recipes/configure.rb

on line 54:
<pre>
    { type: :string, name:  'TargetGroup', data: conf['update_group'] },
</pre>

should be:

<pre>
    { type: :string, name: 'TargetGroup', data: conf['update_group'] ? conf['update_group'] : '' },
</pre>

to be idempotent when node['wsus_client']['update_group'] is nil.

Regards,

**Comment by jmauro** [comment]
Hello @lbn-aaio-team,

Thanks for the report, we'll look into it and keep you posted.

Regards, 
JM

**Comment by rosario-mattera** [comment]
Hi,
I'm facing the same behavior. Is it normal?

Regards,
Rosario

**Comment by Annih** [comment]
Hello,

Hum, no this is not normal.

**Comment by lbn-chef-team** [comment]
Hello, 

it seems that v2.0.0 does not fix the problem and this resource still not idempotent. I think the following modification is not correct: https://github.com/criteo-cookbooks/wsus-client/commit/43a6e78aee79994493da91964cb29607fdab5fce

should be 
` { type: :string, name:                   'TargetGroup', data:                    conf['update_group']  || '' },`
or 
` { type: :string, name: 'TargetGroup', data: conf['update_group'] ? conf['update_group'] : '' },`

Regards,

**Comment by Annih** [comment]
The fix is clearly wrong.

**Comment by axelrtgs** [comment]
there is a PR already that fixes this, merging it would be nice.

**Comment by Annih** [comment]
Released in *2.0.2*

**Comment by axelrtgs** [comment]
Thanks
