### ISSUE TITLE
wsus-client doesn't restart nodes after installation

### ISSUE THREAD

**Issue by rosario-mattera** [criteo-cookbooks/wsus-client#28]
Hi,
after the installation of the updates retrieved from the WSUS server, the wsus-client doesn't reboot the node, even if the installed update(s) require a reboot of the system.

I've set the attribute in this way

`# Disables automatic reboot with logged-on users.
default['wsus_client']['no_reboot_with_logged_users']              = false
`

How could it be solved?

**Comment by Annih** [comment]
Hello @rosario-mattera 

You can use the `reboot` resource to ask chef to reboot if it is required

**Comment by rosario-mattera** [comment]
OK. Thus, I have to modify the recipe, is it right?

**Comment by rosario-mattera** [comment]
Anyway, the only resources available are :download and :install

**Comment by Annih** [comment]
Either you handle the reboot in your own cookbook wrapper.
Either you create a PR to extend the behavior of the update recipe with a new "reboot" feature (which is great)

**Comment by rosario-mattera** [comment]
So, the feature has not been implemented.

I'll do on my own.

Best regards,
Rosario
