### ISSUE TITLE
wsus-client requires two executions to download and install pending updates

### ISSUE THREAD

**Issue by rosario-mattera** [criteo-cookbooks/wsus-client#29]
Hi,
using a host registered on the WSUS server, once the update has been approved on WSUS server, the hosts needs two execution of the recipe to install the KB. Is this the excepted behavior?

Regards,
Rosario

**Comment by Annih** [comment]
Could you describe what happens during the first execution?
Could you also provide us more info about how you use this cookbook and/or Windows update logs (c:\windowsupdate.logs)

Thanks

**Comment by rosario-mattera** [comment]
During the execution of the recipe, the log is

* wsus_client_update[WSUS updates] action download (up to date)

What I'm thinking about is that maybe, after I've approved the update, the WSUS server starts to download the KB. Thus if I try install the update using the recipe, the package has not been download yet on the WSUS server. That's why the behavior. What do you think?

**Comment by rosario-mattera** [comment]
Yes,
as I've guessed, the first execution doesn't download and install the updates because the WSUS server is still downloading them.

Regards,
Rosario
