### ISSUE TITLE
wuauserv always restart each time

### ISSUE THREAD

**Issue by rosario-mattera** [criteo-cookbooks/wsus-client#31]
Hi,
I've deployed the recipe configuring the chef-client to be executed each two hours as well as defined a WSUS server and the Target Group. What it happens is that the wuauserv is always not running so it's always restarted. What do you suggest?

Regards,
Rosario

**Comment by Annih** [comment]
Hello @rosario-mattera 

Thanks for your feedback, this is a known issue... the `wuauserv` service automatically shutdown itself when there is nothing more to do.
One solution could be to restart the service after registry changes and that's it, this would fix your issue.
The downside is that in case of error between the registry and the restart, we might loose the chef notification.

**Comment by rosario-mattera** [comment]
Hello @Annih 
could you please give me some details about the proposed solution?

Regards,
Rosario
