### ISSUE TITLE
Windows server 2016

### ISSUE THREAD

**Issue by rosario-mattera** [criteo-cookbooks/wsus-client#32]
Hi,
have you any plan to upgrade the code for Windows server 2016 hosts?

Regards,
Rosario

**Comment by Annih** [comment]
Hello @rosario-mattera 
What do you mean by that? Did you encounter any issue running *wsus-client* on a Windows Server 2016?

**Comment by rosario-mattera** [comment]
I'm experiencing the error code 0x8024401c and I've seen that the command wuauclt /detectnow has been erased on Windows Server 2016 hosts as well.

**Comment by rosario-mattera** [comment]
I've resolved in this way. For other ones will experiencing this issue, first of all install the KB 3095113 as described here.
https://support.microsoft.com/en-us/help/3095113/update-to-enable-wsus-support-for-windows-10-feature-upgrades

If you have already sync'ed the WSUS, prior of the KB installation, clean the WSUS DB via the following procedure:
https://blogs.technet.microsoft.com/wsus/2016/01/29/how-to-delete-upgrades-in-wsus/

At the end, modify the IIS settings as described here:
http://ininformationtechnologyworld.blogspot.it/2017/06/fixed-wsus-2016-error-code-0x8024401c.html

Regards,
Rosario

**Comment by Annih** [comment]
@rosario-mattera I'm not sure to understand your workaround. The link you pasted are for WSUS Server not clients.
Is your WSUS server on 2012R2?

**Comment by rosario-mattera** [comment]
Yes, my WSUS server is on 2012 R2, but if I tried to sync 2016 servers, there was the error 0x8024401c on the clients. The root cause is that the WSUS server is not able, in the standard installation, to parse 2016 KBs as well as 2016 hosts information. Thus, the procedure described above is requested to upgrade the WSUS server to manage 2016 hosts.
