### ISSUE TITLE
Not possible to configure automatic_update_behavior from role

### ISSUE THREAD

**Issue by GoodMirek** [criteo-cookbooks/wsus-client#7]
It is not possible to set 'automatic_update_behavior' from role.rb role.json, because its datatype is symbol and it is not supported.
Would it be possible to add an option to pass a string as well?

**Comment by Annih** [comment]
Hello @GoodMirek 

Thanks for your feedback, a new version is already planned to improve the `update` recipe and fix some bugs. We'll take time to fix your issue at the same time and allow both string and symbol to configure attributes.

Stay tuned!
