### ISSUE TITLE
Fatal error occurs while running wsus-client::configure

### ISSUE THREAD

**Issue by GoodMirek** [criteo-cookbooks/wsus-client#8]
Chef client version 12.3.0
Windows 2012 R2

Fatal error occurs while running wsus-client::configure
FATAL: Chef::Exceptions::InvalidResourceSpecification: The string `execute' is not valid for resource collection lookup. Correct syntax is `resource_type[resource_name]'

The issue is caused by the line commented below (excerpt from configure.rb):
service 'wuauserv' do
  supports status: true, start: true, stop: true, restart: true
  action [:start, :enable]
#  notifies :run, 'execute', :immediately
end

**Comment by Annih** [comment]
Hi @GoodMirek,

As mentioned in #7 we already spotted this bug, and will provide a fix really soon.

Thanks again for your feedback :)
